template-parts/navbar.php
=> Nav update

index.php
=> first change for feature branch

template-parts/navbar.php
changes to nav want to go to staging please
=> James development branch 1

index.php
Added a click event to the second button in the second horizontal row to show an alert.
=> added some fucntionality to the second button

template-parts/navbar.php
I have added two new menu items for you xxx
=> new menu items

index.php
=> New slider feature

index.php
=> "added header images"

index.php
=> images code now added to index

template-parts/navbar.php
=> New links in menu

template-parts/header.php
=> Fontawesome

index.php
Please add images for the place holders
=> Images added agian

index.php
=> fixed broken images and added additional pagnination

index.php
=> the images again

contact.php
=> New contact page

contact.php, css/customisations.css
=> styling form

contact.php, css/customisations.css
=> Contact branch

index.php, template-parts/footer.php, template-parts/header.php
=> added jqueryui and accordian

index.php
=> second commit for slider

index.php
=> third home slider change

index.php
=> Nick c branch

template-parts/navbar.php
=> New menu links

twitterfeed.php
=> Added twitter feed page

index.php
removed loads of content from homepage
=> removed some junk

contact.php
You probably don;t want to do this.....
=> Changed back to top wording

index.php
=> my new forking update
